### ISSUE TITLE
Improve isolation in HSM (for reuse and export) 

### ISSUE THREAD

**Issue by aleneum** [pytransitions/transitions#362]
Currently, it can be tough to reuse modules if the content and state names are not known (see #332).

### Current Issues

* name collision: Since all callbacks/convenience functions are added to the same (set of) model(s), there is a risk of
* configuration is tricky: you cannot just assign a machine as a substate and be done with it

### Required (currently available) features

* dispatch: unknown events in submachine should be dispatched to parents
* override: it should be possible to hook into submachine events and override behaviour

### New Features

* it should not be necessary to tinker with models when adding a machine to an HSM
* nested models could be used to avoid collisions
* `Machine.states` may only contain root level states and forwards event_handling to `NestedState` if necessary

```yaml
NestedState:
    name: 'StateName'
    states: []  # list of NestedState
    models: []  # list of local models  
```
